osx_image: xcode11.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
# - pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.locations.xcworkspace
  -scheme com.awareframework.ios.sensor.locations-Example -sdk iphonesimulator
  -destination OS=12.2,name="iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  -allowProvisioningUpdates | XCPRETTY
deploy:
  provider: script
  script: "./scripts/release.sh"
  on:
    tags: true
after_success:
- echo 'success!'
env:
  global:
  - secure: UvTSukhyPHAUiF4Y2f12c0obAn/zuiy7c5sVOulDOU89NGWedCg57mf6XWNOTfevLxLfdls2hc8iasMd6jOP1Rf06d0RDX+2nLOi2+nXN9bI1HmhbtkETlXhkuGW7zEZceSl3Y3lepgNh6Auuxlcx74wgd5g1L78wVJvwrmoLJyFSQdKXJxSbWoA742UQBN1vxPFCycLa4X7YQOxKM4rE0/oTagYA8TlYoN01DJyVwxHp5WhHwSF1mHSNOxylBUtglg5rqsgitLM/CR5NCBQmdJjFRaS462mQTeuL4AvaFyGRLdGeGDCDd+nDWxVmM0E2+nLeTE7CYA2Hb9h4OEi6v5LCd/fH5e7pHuADrz7HHUM0rOQC3LFwScHn5nlpQ6PzD6+R47UOacax9ElzrYecR6rYCrvcdvzpkvKUglkSUGLfJqhBMBBLbDZrhIrcjeu2zsADkrKZf+4Lzb+giiVCdnMILVawt+HkBBC7+VIZi2RMhDkuCQVZXVfv1qwKsonN0iK3QOIUwVh7fdtnucdOiXCM2VYTfG0V2lMVW6I1vvkqmE2r0rQnTmnKZtgtH0vB2iZiuXwRAyLeOtjYzGd8MY7u3DsWWY4t7SQfHEfulSPl7cV6uxzX7LRiKwkXEdsdVT2lRyKw1Fl/td6tZ6+6W8a/WNCE8ueTMJT3C8HHrU=
  - secure: WMkhP0ckJi+sIxd0yZPtuOI0Bbo22MWVpesELsBaSy6ITLWUVueC6/97Uq2dlpGqeQ/zzZ5AU3KrAKDOsgd5nTNQ0Yqj2qG6bR9lZkURdCsuZWuiVqscV/sHuR87CV3ydEElOLC9rCa+UyCnl2REb4ibSndqyvDpgk3A3GxtZHcz7aW03o8pDIvPechsLBbA9LDkAk4UCGw4iUq2YCyNBaBvCqFVztzfaxUd+BO5uiLj70ym46zZ4j2gLlbJysD4ikEy0JfCFr7Uk5Rne+V4blZKUecSubVIF1zH5AGQKqjkBm/I3Mr9tISImEqk5yoFTUq73fOPIutx8sJMVeN3z/8snb5c4Q363DCiMI/6AXfCJHQvkPlYVjTOg9zYZEaoVWhpbKPSv9MK6+gp6B9WLLyCD2jtvtNVanM+BGlF+9cHBfIceKZ6T6YNwbXGxc4g1slkuU+jaU+KwnuuZjQdfpao+gIc5RaZ4p/jL9j0R0D11PtO0/MfNysadIyIZiq5qi3SMpyqx824N6e0M2JkYIRGFcvEk5fu9/dYG6zqiePlv1p+yHxZS/BgZXofQppHhiWvbWMWk3q6zUqQd4ake6t0zanmtkPUcrHzgZQVF6LC+Rln2wI0eip2EKJXz00+dM9qoPc8mRZP2TKgPcqS+xlB3gf6Ps2YgHvPBqSByUs=
notifications:
  slack:
    secure: MvswRZ4SfApWWt5RsLggov79jRY6xZ/w9uZZ5lDsfDFp1dO3OrOiLAgb2ejISjpf2MMeWS+lpaeK9nMAwW/jSP5s1TQpqacdQkzgHW0q3ncOZPQP10izIbYxPq7wlBqX223vSDDhS8gbxvROo/lyZnK9EadYpSP6jCwMiX6F8NQoaAR1EWSSjPXYCdmkbGseyGOv+LmZV7X17p1iMlENm6FmLclI/S0P4v5s2YJwDEgex69ppw5vUyfD6LzY2CWiGSFVzx+8dafHCZe9UdhcpeUXYRl55v5womJCeqedYeeLSBWXAnfDLjvxykNb2quJhEEBsTGqGohIykdqTNQY9kzgdwv+wGEVNG9jNwTppzzNnIs6WactxFgNhhtcrDXYtEKP3M/Fa6AazC/gnXwGopIhy7sJq/Y3DP5kxGQ9bg6ojT3MEyyHT69QHUNpaOXSYqJONSjCmarsojFCy9V6jIfUiA/41oB0jUN1uY4/JI4G5z+qClRjQvWfO2z3KQ6eKZiLaLzg9CjLfzEBZc6+rTtdClc/DjM8M9E1eFG4HwIjGeJSloRTSseGDhF0V37Dg56yLX24k1Lz6yU/2YM/wcc7gkdes+Z5BGyfv4R4+HlIAilu747sfFEga0FkUTrq9VYXRDZOgO1o5pGIh4MSo0Sh2euHyE8mNchYdGMLdI4=
